@rem This script invokes the most recently built Python with all arguments
@rem passed through to the interpreter.  This file is generated by the
@rem build process and any changes *will* be thrown away by the next
@rem rebuild.
@rem This is only meant as a convenience for developing CPython
@rem and using it outside of that context is ill-advised.
@echo CPython 3.10.0 Beta 3. Compiled by Fernando Ochoa O. On day Jun 27 2021, at hour 00:49:01. My mail: fochoao(at)pm.me
@setlocal
@set PYTHONHOME=C:\cpython\

@"C:\cpython\python.exe" %*
